// Demo data — clearly marked as DEMO
// Replace with Supabase queries when credentials are configured
// All structures match the TypeScript types for seamless migration

import type { Product, Category, Brand, Service, Solution, Project, BlogPost } from '@/types';

// ============================================================
// CATEGORIES (DEMO)
// ============================================================
export const demoCategories: Category[] = [
  {
    id: '1',
    name: 'Domótica',
    slug: 'domotica',
    description: 'Soluciones de automatización inteligente para tu hogar. Controla iluminación, climatización, seguridad y más desde tu smartphone o por voz.',
    image: '/images/categories/domotica.jpg',
    icon: 'Home',
    seo_title: 'Domótica | Automatización del Hogar | Norman Technologies',
    seo_description: 'Descubre soluciones de domótica para tu hogar en Lima. Iluminación inteligente, control por voz, climatización y seguridad automatizada.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Apagadores Inteligentes',
    slug: 'apagadores-inteligentes',
    description: 'Reemplaza los apagadores convencionales de tu hogar por unos inteligentes. Controla tus luces, programa encendidos, control por voz y a distancia.',
    image: '/images/categories/apagadores.jpg',
    icon: 'ToggleRight',
    seo_title: 'Apagadores Inteligentes WiFi | Norman Technologies',
    seo_description: 'Apagadores inteligentes WiFi touch para automatización y control de iluminación. Programa encendidos y controla por voz.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Audio',
    slug: 'audio',
    description: 'Sistemas de audio multizona y profesional. Disfruta de la música en cada espacio con la mejor calidad de sonido.',
    image: '/images/categories/audio.jpg',
    icon: 'Volume2',
    seo_title: 'Audio Multizona y Profesional | Norman Technologies',
    seo_description: 'Sistemas de audio multizona, audio profesional y sonido envolvente para hogares y empresas en Lima.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Video',
    slug: 'video',
    description: 'Soluciones de video profesional, proyectores, ecrans y sistemas de cine en casa de alta definición.',
    image: '/images/categories/video.jpg',
    icon: 'Monitor',
    seo_title: 'Video Profesional y Cine en Casa | Norman Technologies',
    seo_description: 'Proyectores, ecrans y sistemas de cine en casa con imagen 8K y sonido surround en Lima.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Cámaras de Seguridad',
    slug: 'camaras-de-seguridad',
    description: 'Monitorea tu hogar u oficina desde cualquier parte. Cámaras IP, CCTV, reconocimiento facial y analítica de video.',
    image: '/images/categories/camaras.jpg',
    icon: 'Camera',
    seo_title: 'Cámaras de Seguridad | CCTV | Norman Technologies',
    seo_description: 'Cámaras de seguridad, sistemas CCTV y reconocimiento facial para hogares y empresas en Lima.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'CCTV',
    slug: 'cctv',
    description: 'Circuitos cerrados de cámaras de vigilancia profesional para máxima seguridad y control.',
    image: '/images/categories/cctv.jpg',
    icon: 'Eye',
    seo_title: 'Sistemas CCTV Profesional | Norman Technologies',
    seo_description: 'Sistemas CCTV profesional con reconocimiento facial, control de aforo y análisis vehicular en Lima.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '7',
    name: 'Control de Acceso',
    slug: 'control-de-acceso',
    description: 'Sistemas de control de acceso y asistencia: huelleros, reloj biométrico, detección facial y tarjetas de proximidad.',
    image: '/images/categories/acceso.jpg',
    icon: 'Fingerprint',
    seo_title: 'Control de Acceso Biométrico | Norman Technologies',
    seo_description: 'Sistemas de control de acceso biométrico, huelleros, detección facial y tarjetas de proximidad en Lima.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Redes',
    slug: 'redes',
    description: 'Redes inalámbricas y cableadas de alta performance. Cobertura al 100% sin puntos de sombra.',
    image: '/images/categories/redes.jpg',
    icon: 'Wifi',
    seo_title: 'Redes WiFi Profesionales | Norman Technologies',
    seo_description: 'Instalación de redes WiFi profesionales con cobertura al 100% para hogares y oficinas en Lima.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '9',
    name: 'Video Wall',
    slug: 'video-wall',
    description: 'Soluciones de Video Wall para publicidad, conciertos, eventos corporativos y señalética digital.',
    image: '/images/categories/videowall.jpg',
    icon: 'LayoutGrid',
    seo_title: 'Video Wall Profesional | Norman Technologies',
    seo_description: 'Venta e instalación de Video Wall para publicidad, eventos corporativos y señalética digital en Lima.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '10',
    name: 'Cine en Casa',
    slug: 'cine-en-casa',
    description: 'Experiencia de cine real en tu hogar. Proyectores desde 100" hasta 300", imagen 8K y sonido surround.',
    image: '/images/categories/cine.jpg',
    icon: 'Film',
    seo_title: 'Cine en Casa | Home Theater | Norman Technologies',
    seo_description: 'Sistemas de cine en casa con proyectores de 100" a 300", sonido surround y control inteligente en Lima.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '11',
    name: 'Audio Profesional',
    slug: 'audio-profesional',
    description: 'Sistemas de audio profesional y comercial. Line Array, audio para auditorios e instalaciones completas.',
    image: '/images/categories/audio-pro.jpg',
    icon: 'Speaker',
    seo_title: 'Audio Profesional Comercial | Norman Technologies',
    seo_description: 'Sistemas de audio profesional, Line Array y equipo de audio para auditorios y eventos en Lima.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '12',
    name: 'Telefonía / Intercom',
    slug: 'telefonia-intercom',
    description: 'Sistemas de telefonía interna e intercom para comunicación eficiente en hogares y empresas.',
    image: '/images/categories/intercom.jpg',
    icon: 'Phone',
    seo_title: 'Telefonía e Intercom | Norman Technologies',
    seo_description: 'Sistemas de telefonía interna e intercom profesional para hogares y empresas en Lima.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '13',
    name: 'Automatización Corporativa',
    slug: 'automatizacion-corporativa',
    description: 'Automatización de oficinas, salas de reuniones y espacios corporativos inteligentes.',
    image: '/images/categories/corporativo.jpg',
    icon: 'Building2',
    seo_title: 'Automatización Corporativa | Norman Technologies',
    seo_description: 'Soluciones de automatización corporativa, oficinas inteligentes y salas de conferencias en Lima.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '14',
    name: 'Proyectores',
    slug: 'proyectores',
    description: 'Proyectores profesionales de alta gama para cine en casa, oficinas y auditorios.',
    image: '/images/categories/proyectores.jpg',
    icon: 'Projector',
    seo_title: 'Proyectores Profesionales | Norman Technologies',
    seo_description: 'Proyectores profesionales de alta gama para cine en casa y presentaciones corporativas en Lima.',
    active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// ============================================================
// BRANDS (DEMO)
// ============================================================
export const demoBrands: Brand[] = [
  {
    id: '1', name: 'Control4', slug: 'control4', logo: null,
    description: 'Líder en automatización del hogar', active: true,
    created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2', name: 'Sonos', slug: 'sonos', logo: null,
    description: 'Audio inalámbrico premium', active: true,
    created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3', name: 'Hikvision', slug: 'hikvision', logo: null,
    description: 'Soluciones de videovigilancia', active: true,
    created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4', name: 'Lutron', slug: 'lutron', logo: null,
    description: 'Control de iluminación inteligente', active: true,
    created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5', name: 'Epson', slug: 'epson', logo: null,
    description: 'Proyectores profesionales', active: true,
    created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6', name: 'JBL Professional', slug: 'jbl-professional', logo: null,
    description: 'Audio profesional', active: true,
    created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z',
  },
];

// ============================================================
// PRODUCTS (DEMO)
// ============================================================
export const demoProducts: Product[] = [
  {
    id: '1',
    category_id: '2',
    brand_id: '4',
    name: 'Apagador Inteligente WiFi Touch',
    slug: 'apagador-inteligente-wifi-touch',
    short_description: 'Control inteligente de iluminación con pantalla touch, compatible con Alexa y Google Home.',
    description: 'Reemplaza los apagadores convencionales de tu hogar por unos inteligentes. Los apagadores touch WiFi permiten controlar tus luces, programar encendidos, temporizar y controlar a distancia desde tu smartphone. Compatible con asistentes de voz como Alexa y Google Assistant.',
    features: ['Control por voz con Alexa y Google', 'Pantalla touch capacitiva', 'Programación de horarios', 'Control remoto vía WiFi', 'Diseño elegante y discreto', 'Fácil instalación'],
    specifications: { 'Conectividad': 'WiFi 2.4GHz', 'Voltaje': '100-240V AC', 'Carga máxima': '600W', 'Material': 'Vidrio templado', 'Compatibilidad': 'Alexa, Google Home' },
    sku: 'NT-SW-001',
    featured: true,
    active: true,
    image: '/images/products/apagador-touch.png',
    seo_title: 'Apagador Inteligente WiFi Touch | Norman Technologies',
    seo_description: 'Apagador inteligente WiFi touch con control por voz. Compatible con Alexa y Google Home. Automatiza tu iluminación.',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    category_id: '5',
    brand_id: '3',
    name: 'Cámara IP 4MP con Reconocimiento Facial',
    slug: 'camara-ip-4mp-reconocimiento-facial',
    short_description: 'Cámara de seguridad IP 4MP con reconocimiento facial e inteligencia artificial.',
    description: 'Cámara de seguridad IP con resolución 4MP y reconocimiento facial avanzado. Monitorea tu hogar o negocio desde cualquier lugar con tu smartphone. Visión nocturna, detección de movimiento inteligente y almacenamiento en la nube.',
    features: ['Resolución 4MP Ultra HD', 'Reconocimiento facial AI', 'Visión nocturna 30m', 'Detección de movimiento inteligente', 'App móvil para monitoreo remoto', 'Almacenamiento en nube o NVR'],
    specifications: { 'Resolución': '4MP (2560x1440)', 'Visión nocturna': '30 metros', 'Ángulo de visión': '120°', 'Conectividad': 'PoE / WiFi', 'Protección': 'IP67' },
    sku: 'NT-CAM-001',
    featured: true,
    active: true,
    image: '/images/products/camara-4mp.png',
    seo_title: 'Cámara IP 4MP Reconocimiento Facial | Norman Technologies',
    seo_description: 'Cámara de seguridad IP 4MP con reconocimiento facial y monitoreo remoto. Ideal para hogares y empresas en Lima.',
    created_at: '2024-01-20T00:00:00Z',
    updated_at: '2024-01-20T00:00:00Z',
  },
  {
    id: '3',
    category_id: '3',
    brand_id: '2',
    name: 'Sistema de Audio Multizona Inalámbrico',
    slug: 'sistema-audio-multizona-inalambrico',
    short_description: 'Audio en cada ambiente de tu hogar. Controla la música por zonas desde tu smartphone.',
    description: 'Sistema de audio multizona que permite disfrutar de música independiente en cada ambiente. Integración con Spotify, Apple Music y más. Control total desde tu smartphone o por voz. Diseño discreto que se integra con la estética de tu hogar.',
    features: ['Audio independiente por zonas', 'Streaming desde Spotify, Apple Music', 'Control por voz con Alexa', 'Diseño discreto empotrable', 'Calidad Hi-Fi', 'Expansible hasta 32 zonas'],
    specifications: { 'Potencia': '55W por canal', 'Zonas': 'Hasta 32', 'Conectividad': 'WiFi, AirPlay 2, Bluetooth', 'Formato': 'Empotrable / Superficie' },
    sku: 'NT-AUD-001',
    featured: true,
    active: true,
    image: '/images/products/audio-multizona.png',
    seo_title: 'Audio Multizona Inalámbrico | Norman Technologies',
    seo_description: 'Sistema de audio multizona inalámbrico con Spotify y control por voz. Música en cada ambiente de tu hogar.',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
  {
    id: '4',
    category_id: '10',
    brand_id: '5',
    name: 'Proyector 4K Laser Home Cinema',
    slug: 'proyector-4k-laser-home-cinema',
    short_description: 'Proyector láser 4K para cine en casa con imagen de 100" a 300" y alta luminosidad.',
    description: 'Proyector láser 4K de alta gama para cine en casa. Imagen en alta definición desde 100" hasta 300". Compatible con HDR10+ y Dolby Vision. Conectividad completa para integración con sistemas de domótica.',
    features: ['Resolución 4K nativa', 'Tecnología láser (vida útil 20,000 hrs)', 'HDR10+ y Dolby Vision', 'Tamaño de imagen: 100" a 300"', 'Conectividad HDMI 2.1, USB, WiFi', 'Bajo ruido de operación'],
    specifications: { 'Resolución': '3840x2160 (4K)', 'Luminosidad': '3,200 lúmenes', 'Contraste': '2,500,000:1', 'Fuente de luz': 'Láser', 'Vida útil': '20,000 horas' },
    sku: 'NT-PRO-001',
    featured: true,
    active: true,
    image: '/images/products/proyector-4k.png',
    seo_title: 'Proyector 4K Laser Cine en Casa | Norman Technologies',
    seo_description: 'Proyector láser 4K para cine en casa. Imagen de 100" a 300" con HDR10+ y Dolby Vision.',
    created_at: '2024-02-10T00:00:00Z',
    updated_at: '2024-02-10T00:00:00Z',
  },
  {
    id: '5',
    category_id: '7',
    brand_id: '3',
    name: 'Control de Acceso Biométrico Facial',
    slug: 'control-acceso-biometrico-facial',
    short_description: 'Sistema de control de acceso con detección facial, huellero y tarjetas de proximidad.',
    description: 'Sistema de control de acceso y asistencia con múltiples métodos de verificación: detección facial, huella digital y tarjetas de proximidad. Ideal para empresas y edificios corporativos.',
    features: ['Detección facial avanzada', 'Lector de huellas dactilares', 'Tarjetas de proximidad RFID', 'Reloj biométrico integrado', 'Reportes de asistencia', 'Control de puertas'],
    specifications: { 'Capacidad': '10,000 rostros', 'Verificación': 'Facial + Huella + Tarjeta', 'Pantalla': '7" touch', 'Conectividad': 'TCP/IP, WiFi', 'Temperatura': 'Sensor integrado' },
    sku: 'NT-ACC-001',
    featured: true,
    active: true,
    image: '/images/products/control-acceso.png',
    seo_title: 'Control de Acceso Biométrico Facial | Norman Technologies',
    seo_description: 'Control de acceso biométrico con detección facial, huella digital y tarjetas de proximidad para empresas.',
    created_at: '2024-02-15T00:00:00Z',
    updated_at: '2024-02-15T00:00:00Z',
  },
  {
    id: '6',
    category_id: '9',
    brand_id: null,
    name: 'Video Wall LED 2x2 Profesional',
    slug: 'video-wall-led-2x2-profesional',
    short_description: 'Video Wall LED profesional 2x2 para publicidad, eventos y señalética digital.',
    description: 'Video Wall LED profesional de configuración 2x2 con bisel ultra delgado. Ideal para publicidad, conciertos, eventos corporativos y señalética digital. Administración remota de contenidos.',
    features: ['Bisel ultra delgado 1.7mm', 'Brillo 500 nits', 'Operación 24/7', 'Administración remota', 'Señalética digital integrada', 'Soporte de pared incluido'],
    specifications: { 'Configuración': '2x2 (4 paneles)', 'Resolución total': '3840x2160', 'Bisel': '1.7mm', 'Brillo': '500 nits', 'Vida útil': '60,000 horas' },
    sku: 'NT-VW-001',
    featured: true,
    active: true,
    image: null,
    seo_title: 'Video Wall LED 2x2 Profesional | Norman Technologies',
    seo_description: 'Video Wall LED profesional 2x2 para publicidad y eventos. Bisel ultra delgado y operación 24/7.',
    created_at: '2024-02-20T00:00:00Z',
    updated_at: '2024-02-20T00:00:00Z',
  },
];

// ============================================================
// SERVICES (DEMO — based on PDF)
// ============================================================
export const demoServices: Service[] = [
  {
    id: '1',
    name: 'Instalación',
    slug: 'instalacion',
    short_description: 'Instalación profesional de todos nuestros sistemas y equipos tecnológicos.',
    description: 'Realizamos la instalación profesional de todos nuestros sistemas y equipos. Nuestro equipo técnico garantiza una implementación impecable, respetando la estética del espacio y siguiendo los más altos estándares de calidad. Trabajamos con componentes de alta calidad, discretamente montados y en armonía con la estética del lugar.',
    icon: 'Wrench',
    image: '/images/services/instalacion.jpg',
    features: ['Instalación certificada', 'Montaje discreto y elegante', 'Configuración completa', 'Pruebas de funcionamiento', 'Capacitación al usuario'],
    active: true,
    order: 1,
    seo_title: 'Instalación Profesional de Sistemas Tecnológicos | Norman Technologies',
    seo_description: 'Servicio de instalación profesional de sistemas de domótica, audio, video y seguridad en Lima.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Mantenimiento',
    slug: 'mantenimiento',
    short_description: 'Mantenimiento preventivo y correctivo para asegurar el óptimo funcionamiento de tus sistemas.',
    description: 'Ofrecemos servicio de mantenimiento preventivo y correctivo para todos los sistemas instalados. Nos aseguramos de que tu inversión en tecnología se mantenga funcionando de manera óptima y eficiente a lo largo del tiempo.',
    icon: 'Settings',
    image: '/images/services/mantenimiento.jpg',
    features: ['Mantenimiento preventivo', 'Mantenimiento correctivo', 'Diagnóstico técnico', 'Actualización de firmware', 'Soporte técnico continuo'],
    active: true,
    order: 2,
    seo_title: 'Mantenimiento de Sistemas Tecnológicos | Norman Technologies',
    seo_description: 'Servicio de mantenimiento preventivo y correctivo de sistemas de domótica y automatización en Lima.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Diseño',
    slug: 'diseno',
    short_description: 'Diseño personalizado de soluciones tecnológicas adaptadas a tu espacio y necesidades.',
    description: 'Diseñamos soluciones tecnológicas a medida, adaptadas a las necesidades específicas de cada cliente y espacio. Nuestro proceso de diseño contempla la funcionalidad, la estética y la escalabilidad de cada proyecto.',
    icon: 'PenTool',
    image: '/images/services/diseno.jpg',
    features: ['Diseño a medida', 'Evaluación del espacio', 'Propuesta técnica y visual', 'Integración con arquitectura', 'Escalabilidad futura'],
    active: true,
    order: 3,
    seo_title: 'Diseño de Soluciones Tecnológicas | Norman Technologies',
    seo_description: 'Diseño personalizado de soluciones de domótica y automatización para hogares y empresas en Lima.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Automatización',
    slug: 'automatizacion',
    short_description: 'Automatización integral de espacios residenciales, comerciales y corporativos.',
    description: 'Nuestro sistema de automatización coordina la tecnología de tu hogar o empresa para brindarte el mayor confort y la nueva experiencia de interactuar con tu espacio. Ten el control completo de manera práctica y eficaz.',
    icon: 'Cpu',
    image: '/images/services/automatizacion.jpg',
    features: ['Automatización residencial', 'Automatización comercial', 'Automatización corporativa', 'Integración de sistemas', 'Control centralizado'],
    active: true,
    order: 4,
    seo_title: 'Automatización de Espacios | Norman Technologies',
    seo_description: 'Servicio de automatización integral para hogares, oficinas y espacios corporativos en Lima.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Implementación de Sistemas',
    slug: 'implementacion-de-sistemas',
    short_description: 'Implementación completa de sistemas de audio, video, seguridad y automatización.',
    description: 'Realizamos la implementación completa de sistemas tecnológicos, desde la planificación hasta la puesta en marcha. Habilitamos salas de conferencias, auditorios, sistemas de seguridad y más con tecnología de punta.',
    icon: 'Layers',
    image: '/images/services/implementacion.jpg',
    features: ['Planificación integral', 'Implementación llave en mano', 'Integración de múltiples sistemas', 'Capacitación operativa', 'Soporte post-implementación'],
    active: true,
    order: 5,
    seo_title: 'Implementación de Sistemas Tecnológicos | Norman Technologies',
    seo_description: 'Implementación completa de sistemas de audio, video, seguridad y automatización en Lima.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Integración Tecnológica',
    slug: 'integracion-tecnologica',
    short_description: 'Integración de múltiples sistemas tecnológicos en una plataforma unificada.',
    description: 'Integramos diferentes sistemas tecnológicos para que trabajen en conjunto de forma armónica. Audio, video, seguridad, iluminación, climatización y más, todo controlado desde una sola plataforma.',
    icon: 'Link',
    image: '/images/services/integracion.jpg',
    features: ['Integración multi-sistema', 'Plataforma unificada de control', 'Interoperabilidad de marcas', 'Automatización de escenas', 'Monitoreo centralizado'],
    active: true,
    order: 6,
    seo_title: 'Integración Tecnológica | Norman Technologies',
    seo_description: 'Servicio de integración de sistemas de domótica, audio, video y seguridad en una plataforma unificada.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// ============================================================
// SOLUTIONS (DEMO — based on PDF)
// ============================================================
export const demoSolutions: Solution[] = [
  // Residencial
  { id: '1', name: 'Casas Inteligentes', slug: 'casas-inteligentes', segment: 'residencial', short_description: 'Automatización completa para tu hogar', description: 'Transforma tu casa en un hogar inteligente con control de iluminación, climatización, seguridad y entretenimiento.', icon: 'Home', image: null, features: ['Iluminación inteligente', 'Climatización automatizada', 'Seguridad integrada', 'Control por voz'], active: true, order: 1, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: '2', name: 'Departamentos', slug: 'departamentos', segment: 'residencial', short_description: 'Domótica adaptada a departamentos', description: 'Soluciones de automatización diseñadas para espacios de departamentos, maximizando confort y eficiencia.', icon: 'Building', image: null, features: ['Diseño para espacios compactos', 'Control centralizado', 'Ahorro energético', 'Seguridad perimetral'], active: true, order: 2, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: '3', name: 'Domótica Residencial', slug: 'domotica-residencial', segment: 'residencial', short_description: 'Sistema completo de automatización del hogar', description: 'Nuestro sistema de automatización coordina la tecnología de tu hogar para brindarte el mayor confort.', icon: 'Cpu', image: null, features: ['Iluminación', 'Seguridad', 'Audio multizona', 'Video portero', 'Climatización', 'Control por voz'], active: true, order: 3, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: '4', name: 'Cine en Casa', slug: 'cine-en-casa-residencial', segment: 'residencial', short_description: 'Experiencia de cine real en tu hogar', description: 'Vive una experiencia similar al cine en el hogar. Imagen en alta definición y el mejor sonido surround.', icon: 'Film', image: null, features: ['Proyectores 100" a 300"', 'Sonido surround', 'Control inteligente', 'Iluminación personalizada'], active: true, order: 4, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: '5', name: 'Seguridad Residencial', slug: 'seguridad-residencial', segment: 'residencial', short_description: 'Protección integral para tu hogar', description: 'Integra cámaras, cerraduras, alarmas y grabadoras digitales en un sistema de domótica unificado.', icon: 'Shield', image: null, features: ['Cámaras de seguridad', 'Cerraduras inteligentes', 'Monitoreo remoto', 'Alertas en tiempo real'], active: true, order: 5, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: '6', name: 'Audio Multizona Residencial', slug: 'audio-multizona-residencial', segment: 'residencial', short_description: 'Música en cada espacio de tu hogar', description: 'Coloca parlantes en cada zona, selecciona música independiente y controla el volumen por ambiente.', icon: 'Music', image: null, features: ['Zonas independientes', 'Streaming integrado', 'Control por app', 'Diseño discreto'], active: true, order: 6, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },

  // Comercial
  { id: '7', name: 'Audio Profesional', slug: 'audio-profesional-comercial', segment: 'comercial', short_description: 'Sistemas de audio comercial y profesional', description: 'Sistemas de audio profesional y comercial con altavoces Line Array y equipo de la más alta calidad.', icon: 'Speaker', image: null, features: ['Line Array', 'Audio para auditorios', 'Sonido comercial', 'Instalación profesional'], active: true, order: 7, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: '8', name: 'CCTV Comercial', slug: 'cctv-comercial', segment: 'comercial', short_description: 'Videovigilancia profesional para negocios', description: 'Circuito cerrado de cámaras de vigilancia con reconocimiento facial, control de aforo y analítica.', icon: 'Eye', image: null, features: ['Reconocimiento facial', 'Control de aforo', 'Análisis vehicular', 'Monitoreo 24/7'], active: true, order: 8, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: '9', name: 'Video Wall Comercial', slug: 'video-wall-comercial', segment: 'comercial', short_description: 'Soluciones de Video Wall para impactar', description: 'Video Wall para publicidad, conciertos, eventos corporativos y señalética digital.', icon: 'LayoutGrid', image: null, features: ['Publicidad digital', 'Eventos corporativos', 'Señalética digital', 'Administración remota'], active: true, order: 9, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: '10', name: 'Seguridad Comercial', slug: 'seguridad-comercial', segment: 'comercial', short_description: 'Seguridad integral para negocios', description: 'Soluciones de seguridad electrónica para comercios y empresas con la más avanzada tecnología.', icon: 'ShieldCheck', image: null, features: ['Control de acceso', 'CCTV profesional', 'Alarmas', 'Monitoreo central'], active: true, order: 10, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: '11', name: 'Control de Acceso', slug: 'control-acceso-comercial', segment: 'comercial', short_description: 'Control de entradas y salidas', description: 'Sistemas de control de acceso y asistencia con huelleros, detección facial y tarjetas de proximidad.', icon: 'Fingerprint', image: null, features: ['Huelleros', 'Reloj biométrico', 'Detección facial', 'Tarjetas de proximidad'], active: true, order: 11, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },

  // Corporativo
  { id: '12', name: 'Oficinas Inteligentes', slug: 'oficinas-inteligentes', segment: 'corporativo', short_description: 'Automatización de espacios corporativos', description: 'Garantiza la optimización del tiempo y la eficiencia del trabajo en equipo con oficinas inteligentes.', icon: 'Building2', image: null, features: ['Pantallas interactivas', 'Audio integrado', 'Colaboración inalámbrica', 'Microfonía profesional'], active: true, order: 12, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: '13', name: 'Salas de Reuniones', slug: 'salas-de-reuniones', segment: 'corporativo', short_description: 'Salas equipadas con tecnología de punta', description: 'Habilitamos salas de conferencias y videoconferencias con la mejor tecnología para reuniones exitosas.', icon: 'Users', image: null, features: ['Videoconferencias', 'Microfonía', 'Pantallas', 'Control automatizado'], active: true, order: 13, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: '14', name: 'Videoconferencias', slug: 'videoconferencias', segment: 'corporativo', short_description: 'Sistemas profesionales de videoconferencia', description: 'Implementación de salas de videoconferencias y ruedas de prensa con la mejor calidad de audio y video.', icon: 'Video', image: null, features: ['Alta definición', 'Audio profesional', 'Colaboración remota', 'Integración con plataformas'], active: true, order: 14, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },

  // Oficinas
  { id: '15', name: 'Automatización de Oficinas', slug: 'automatizacion-oficinas', segment: 'oficinas', short_description: 'Automatización inteligente de oficinas', description: 'Automatización de espacios de oficina para máxima productividad y eficiencia.', icon: 'Zap', image: null, features: ['Iluminación automatizada', 'Climatización inteligente', 'Control de acceso', 'Sensores de presencia'], active: true, order: 15, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
  { id: '16', name: 'Pantallas y Audio para Oficinas', slug: 'pantallas-audio-oficinas', segment: 'oficinas', short_description: 'Equipamiento audiovisual para oficinas', description: 'Soluciones de pantallas y audio profesional para salas de oficinas, directorios y áreas de trabajo.', icon: 'Monitor', image: null, features: ['Pantallas profesionales', 'Audio ambiental', 'Microfonía', 'Señalización digital'], active: true, order: 16, created_at: '2024-01-01T00:00:00Z', updated_at: '2024-01-01T00:00:00Z' },
];

// ============================================================
// PROJECTS (DEMO — empty to avoid inventing)
// ============================================================
export const demoProjects: Project[] = [
  {
    id: '1',
    name: 'Proyecto Residencial Demo',
    slug: 'proyecto-residencial-demo',
    category: 'Domótica',
    description: 'Proyecto de demostración — los proyectos reales se agregarán desde Supabase.',
    solution: 'Domótica Residencial',
    location: 'Lima, Perú',
    date: '2024-01-01',
    image: '/images/projects/proyecto-residencial.png',
    featured: true,
    active: true,
    seo_title: null,
    seo_description: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Proyecto Corporativo Demo',
    slug: 'proyecto-corporativo-demo',
    category: 'Oficinas Inteligentes',
    description: 'Proyecto de demostración — los proyectos reales se agregarán desde Supabase.',
    solution: 'Oficinas Inteligentes',
    location: 'Lima, Perú',
    date: '2024-03-01',
    image: '/images/projects/proyecto-corporativo.png',
    featured: true,
    active: true,
    seo_title: null,
    seo_description: null,
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-03-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Proyecto Audio Profesional Demo',
    slug: 'proyecto-audio-profesional-demo',
    category: 'Audio Profesional',
    description: 'Proyecto de demostración — los proyectos reales se agregarán desde Supabase.',
    solution: 'Audio Profesional',
    location: 'Lima, Perú',
    date: '2024-05-01',
    image: '/images/projects/proyecto-audio.png',
    featured: true,
    active: true,
    seo_title: null,
    seo_description: null,
    created_at: '2024-05-01T00:00:00Z',
    updated_at: '2024-05-01T00:00:00Z',
  },
];

// ============================================================
// BLOG POSTS (DEMO)
// ============================================================
export const demoBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: '¿Qué es la domótica y cómo puede transformar tu hogar?',
    slug: 'que-es-la-domotica',
    excerpt: 'Descubre cómo la domótica puede mejorar tu calidad de vida, ahorrarte energía y brindarte mayor seguridad en tu hogar.',
    content: 'La domótica es la automatización inteligente de tu hogar. Imagina controlar la iluminación, seguridad, climatización y entretenimiento desde tu smartphone o con tu voz...',
    image: '/images/blog/domotica.png',
    category: 'Domótica',
    author: 'Norman Technologies',
    published: true,
    seo_title: '¿Qué es la Domótica? Guía Completa | Norman Technologies',
    seo_description: 'Aprende qué es la domótica, sus beneficios y cómo puede transformar tu hogar en Lima. Guía completa de automatización.',
    published_at: '2024-03-15T00:00:00Z',
    created_at: '2024-03-15T00:00:00Z',
    updated_at: '2024-03-15T00:00:00Z',
  },
  {
    id: '2',
    title: 'Guía de cámaras de seguridad: ¿Cuál elegir para tu hogar o negocio?',
    slug: 'guia-camaras-seguridad',
    excerpt: 'Todo lo que necesitas saber para elegir el sistema de cámaras de seguridad ideal para tu hogar o empresa.',
    content: 'Elegir el sistema de cámaras de seguridad adecuado es fundamental para proteger lo que más importa...',
    image: '/images/blog/seguridad.png',
    category: 'Seguridad',
    author: 'Norman Technologies',
    published: true,
    seo_title: 'Guía de Cámaras de Seguridad | Norman Technologies',
    seo_description: 'Guía completa para elegir cámaras de seguridad para tu hogar o negocio en Lima. CCTV, IP, WiFi y más.',
    published_at: '2024-04-10T00:00:00Z',
    created_at: '2024-04-10T00:00:00Z',
    updated_at: '2024-04-10T00:00:00Z',
  },
  {
    id: '3',
    title: 'Cine en casa: Cómo crear la experiencia perfecta',
    slug: 'cine-en-casa-experiencia-perfecta',
    excerpt: 'Aprende a diseñar tu sala de cine en casa con la mejor tecnología en proyección y sonido surround.',
    content: 'El cine en casa ha evolucionado enormemente. Hoy puedes tener una experiencia cinematográfica real en tu hogar...',
    image: '/images/blog/cine-en-casa.png',
    category: 'Audio',
    author: 'Norman Technologies',
    published: true,
    seo_title: 'Cómo Crear un Cine en Casa | Norman Technologies',
    seo_description: 'Guía para crear un cine en casa con proyectores, sonido surround y control inteligente en Lima.',
    published_at: '2024-05-05T00:00:00Z',
    created_at: '2024-05-05T00:00:00Z',
    updated_at: '2024-05-05T00:00:00Z',
  },
];
